# Generated by Django 4.0.4 on 2022-06-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylist',
            name='favorites',
            field=models.ManyToManyField(to='main_app.album'),
        ),
    ]
