# Generated by Django 4.0.4 on 2022-06-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_album_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['rank_2020']},
        ),
        migrations.RemoveField(
            model_name='album',
            name='rank',
        ),
        migrations.AddField(
            model_name='album',
            name='rank_2003',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='rank_2012',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='rank_2020',
            field=models.IntegerField(default=0),
        ),
    ]
