# Generated by Django 4.0.4 on 2022-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_mylist_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylist',
            name='listened',
            field=models.ManyToManyField(related_name='listened', to='main_app.album'),
        ),
        migrations.AddField(
            model_name='mylist',
            name='not_interested',
            field=models.ManyToManyField(related_name='not_interested', to='main_app.album'),
        ),
        migrations.AddField(
            model_name='mylist',
            name='want_to_listen',
            field=models.ManyToManyField(related_name='want_to_listen', to='main_app.album'),
        ),
        migrations.AlterField(
            model_name='mylist',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='main_app.album'),
        ),
    ]
