# Generated by Django 4.0.4 on 2022-06-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_mylist_listened_mylist_not_interested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_small',
            field=models.CharField(default='', max_length=500),
        ),
    ]
