# Generated by Django 4.0.4 on 2022-06-04 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_album_options_remove_album_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='created_at',
        ),
    ]
