# Generated by Django 4.0.4 on 2022-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlist',
            name='listened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlist',
            name='not_interested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlist',
            name='want_to_listen',
            field=models.BooleanField(default=False),
        ),
    ]
