# Generated by Django 4.0.4 on 2022-06-05 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_userlist_favorite_userlist_listened_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
